---
- name: Install from the APT repository
  ansible.builtin.include_tasks: install_apt.yml
  when: mattermost_install_method == 'apt'

- name: Install from the release tarball
  ansible.builtin.include_tasks: install_tarball.yml
  when: mattermost_install_method == 'tarball'
