---
- name: Create Mattermost group
  ansible.builtin.group:
    name: "{{ mattermost_group }}"
    system: true
    state: present

- name: Create Mattermost system user
  ansible.builtin.user:
    name: "{{ mattermost_user }}"
    group: "{{ mattermost_group }}"
    system: true
    shell: "/usr/sbin/nologin"
    home: "{{ mattermost_install_dir }}"
    create_home: false
    state: present
